
name: ipp
version: 1.0b1
summary: IPP Sample Implementation
description: |
  The ippsample project provides sample implementations of an IPP Client, Proxy,
  Server, and other tools. It is based on the CUPS source code and is maintained
  by the PWG IPP workgroup.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict
icon: server/printer.png

apps:
    server:
        command: sbin/server
        plugs: [avahi-observe, home, network, network-bind]
    find:
        command: bin/find
        plugs: [avahi-observe, home, network]
    proxy:
        command: sbin/proxy
        plugs: [avahi-observe, home, network]
    tool:
        command: bin/tool
        plugs: [avahi-observe, home, network]
    transform:
        command: bin/transform
        plugs: [avahi-observe, home, network]
    transform3d:
        command: bin/transform3d
        plugs: [avahi-observe, home, network]

parts:
    main:
        plugin: autotools
        configflags: [--with-name-prefix=]
        source: .

build-packages: [cura-engine, libavahi-client-dev, libgnutls28-dev, libjpeg-dev, libmupdf-dev, libopenjp2-7-dev, libpng-dev, zlib1g-dev]

